version: "3.3"
services:
  main:
    build:
      context: .
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongodb
  d1:
    build:
      context: .
      dockerfile: game/Dockerfile
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongodb
  d2:
    build:
      context: .
      dockerfile: game/Dockerfile
    environment:
      - SERVER=d2
      - NODE_ENV=dev
    depends_on:
      - mongodb
  tutorial:
    build:
      context: .
      dockerfile: game/Dockerfile
    environment:
      - NODE_ENV=dev
      - SERVER=t2
      - SERVER_TYPE=tutorial
    depends_on:
      - mongodb
  mongodb:
    ports:
      - "6000:6000"
    image: "mongo"
  frontend:
    build:
      context: dev/haproxy
    ports:
      - "5000:5000"
    depends_on:
      - main
      - d1
      - d2
      - tutorial