version: "3.3"
services:
  main:
    build:
      context: .
    env_file: .env
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongodb
      - minio
    volumes:
      - ./public:/usr/src/app/public
      - ./logs:/var/log
  d1:
    build:
      context: .
      dockerfile: game/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongodb
      - minio
      - transpiler
    volumes:
      - ./logs:/var/log
  d2:
    build:
      context: .
      dockerfile: game/Dockerfile
    env_file: .env
    environment:
      - SERVER=d2
      - NODE_ENV=dev
    depends_on:
      - mongodb
      - minio
      - transpiler
    volumes:
      - ./logs:/var/log
  tutorial:
    build:
      context: .
      dockerfile: game/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=dev
      - SERVER=t2
      - SERVER_TYPE=tutorial
    depends_on:
      - mongodb
    volumes:
      - ./logs:/var/log
  mongodb:
    image: "mongo"
  mongo-express:
    image: "mongo-express"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    ports:
      - "6001:8081"
  frontend:
    build:
      context: dev/haproxy
    ports:
      - "5000:5000"
    depends_on:
      - main
      - d1
      - d2
      - tutorial
      - minio
  minio:
    image: "minio/minio:RELEASE.2024-01-01T16-36-33Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address=:9001"]
  transpiler:
    ports:
      - "8075:5000"
    build:
      context: ./transpiler
      dockerfile: Dockerfile
    environment:
      - TRANSPILER_SECRET=${TRANSPILER_SECRET:-default-transpiler-secret}
    volumes:
      - ./logs:/var/log
