infobox_msg = {
	spirit_reference: "<p class='info_h'>Reference to your spirit (an object).</p><p class='info_p'>In the ‘real game’ (outside of this tutorial), this will be your username + #. E.g. arnold4.move...</p>",
	base_reference: "<p class='info_h'>Reference to your base (an object).</p><p class='info_p'>In the ‘real game’ </p>",
	move_method: "<p class='info_h'>The move(<i>target</i>) method tells the spirit where to move to.</p><p class='info_p'><i>target</i> is an [x, y] array representing the x, y coordinates on the game board.</p>",
	star_property_position: "<p class='info_h'>star_zxq is a reference to a star object. Things will be clearer once you start playing.</p><p class='info_p'>Stars are a source of <i>energy</i>. You need <i>energy</i> for everything in this game. Attacking, defending and building new spirits, but more on that later.</p><p class='info_h'>position is a property of all objects in yare.io</p><p class='info_p'><i>[any_object]</i>.position returns an [x, y] array where x and y are the object's coordinates.</p>",
	energize_method0: "<p class='info_h'>The energize(<i>target</i>) method is for transferring energy</p><p class='info_p'><i>target</i> is an object. If target is the same as origin, the spirit will attempt to harvest energy from a nearby star</p>",
	energize_method: "<p class='info_h'>The energize(<i>target</i>) method is for transferring energy</p><p class='info_p'><i>target</i> is an object. If target is the same as origin, the spirit will attempt to harvest energy from a nearby star</p>",
	energize_target_self: "<p class='info_h'>Since <i>target</i> here is the same object as the origin of the energy transfer (s1), the spirit will attempt to harvest energy from a nearby star.</p>",
	if_energy_capacity: "<p class='info_h'>This checks if the spirit has harvested as much energy as it can hold</p>",
	position_property: "<p class='info_h'>position is a property of all objects in yare.io</p><p class='info_p'><i>[any_object]</i>.position returns an [x, y] array where x and y are the object's coordinates.</p>"
}

tutorial_strings = {
	p1: "<p id='tut_helper' class='tutorial_text'>Well done!</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='energize_method0'>energize()</span></code> is the other important method in the game, it tells your spirit where to transfer energy.</p><p id='tut_helper' class='tutorial_text'>Add <code><span class='tut_label' id='spirit_reference'>s1</span><span class='tut_label' id='energize_method'>.energize</span>(<span class='tut_label' id='energize_target_self'>s1</span>)</code><span class='copy_code' code='s1.energize(s1);'>COPY</span> to your code. Hover over this snippet to learn more about what this does</p>",
	p2: "<p id='tut_helper' class='tutorial_text'>Nice, the spirit is now harvesting energy.</p><p id='tut_helper' class='tutorial_text'>Each spirit has a few properties that you can access and use to make decisions. Try it out—check whether spirit’s energy is equal to its energy_capacity and if yes, move it back to base.</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>if (s1.energy == s1.energy_capacity)</span> {<br>&nbsp;&nbsp;<span class='tut_label' id='spirit_reference'>s1</span><span class='tut_label' id='move_method'>.move</span>(<span class='tut_label' id='base_reference'>base</span><span class='tut_label' id='position_property'>.position</span>)<br>&nbsp;&nbsp;s1.energize(base);<br>}</code><br><span class='copy_code' code='if (s1.energy == s1.energy_capacity) {&#10;	s1.move(base.position)&#10;	s1.energize(base);&#10;}'>COPY</span></p>",
	p3: "<p id='tut_helper' class='tutorial_text'>Good, but there is a problem. When the spirit transfers a little bit of energy to the star, the if statement returns false and the command to energize the base is ignored.</p><p id='tut_helper' class='tutorial_text'>One way to fix this is to use a variable to store the spirit’s  activity. Let’s try replacing your entire code with this:</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>var activity = “”;<br><br>if (s1.energy == s1.energy_capacity){ <br>&nbsp;&nbsp; activity = 'charging'; <br>} else if (s1.energy == 0){ <br>&nbsp;&nbsp; activity = 'harvesting'; <br>}<br><br> if (activity == 'charging'){ <br>&nbsp;&nbsp; s1.move(base.position); <br>&nbsp;&nbsp; s1.energize(base); <br>} else if (activity == 'harvesting'){ <br>&nbsp;&nbsp; s1.move(star_zxq.position); <br>&nbsp;&nbsp; s1.energize(s1); <br>}</span></code><br><span class='copy_code' code='s1.energize(base);'>COPY</span></p>"
}
