infobox_msg = {
	spirit_reference: "<p class='info_h'>Reference to your spirit (an object).</p><p class='info_p'>In the ‘real game’ (outside of this tutorial), this will be your username + #. E.g. arnold4.move...</p>",
	base_reference: "<p class='info_h'>Reference to your base (an object).</p><p class='info_p'>In the ‘real game’ </p>",
	move_method: "<p class='info_h'>The move(<i>target</i>) method tells the spirit where to move to.</p><p class='info_p'><i>target</i> is an [x, y] array representing the x, y coordinates on the game board.</p>",
	star_property_position: "<p class='info_h'>star_zxq is a reference to a star object. Things will be clearer once you start playing.</p><p class='info_p'>Stars are a source of <i>energy</i>. You need <i>energy</i> for everything in this game. Attacking, defending and building new spirits, but more on that later.</p><p class='info_h'>position is a property of all objects in yare.io</p><p class='info_p'><i>[any_object]</i>.position returns an [x, y] array where x and y are the object's coordinates.</p>",
	energize_method0: "<p class='info_h'>The energize(<i>target</i>) method is for transferring energy</p><p class='info_p'><i>target</i> is an object. If target is the same as origin, the spirit will attempt to harvest energy from a nearby star</p>",
	energize_method: "<p class='info_h'>The energize(<i>target</i>) method is for transferring energy</p><p class='info_p'><i>target</i> is an object. If target is the same as origin, the spirit will attempt to harvest energy from a nearby star</p>",
	energize_target_self: "<p class='info_h'>Since <i>target</i> here is the same object as the origin of the energy transfer (s1), the spirit will attempt to harvest energy from a nearby star.</p>",
	if_energy_capacity: "<p class='info_h'>This checks if the spirit has harvested as much energy as it can hold</p>",
	position_property: "<p class='info_h'>position is a property of all objects in yare.io</p><p class='info_p'><i>[any_object]</i>.position returns an [x, y] array where x and y are the object's coordinates.</p>",
	memory_intro: "<p class='info_h'>memory is for storing values across ticks</p><p class='info_p'>This is nothing more than an empty, pre-declared object. Store anything, anyhow you want in it.</p>",
	my_spirits0: "<p class='info_h'>Array of your spirits</p><p class='info_p'>Pre-defined array that always contains all of your living spirits, stored as objects.</p><p class='info_p'>E.g. <code>my_spirits[0].move(<i>target</i>)</code> will move your oldest spirit to <i>target</i>.</p>"
}

tutorial_strings = {
	p1: "<p id='tut_helper' class='tutorial_text'>Well done!</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='energize_method0'>energize()</span></code> is the other important method in the game, it tells your spirit where to transfer energy.</p><p id='tut_helper' class='tutorial_text'>Add <code><span class='tut_label' id='spirit_reference'>s1</span><span class='tut_label' id='energize_method'>.energize</span>(<span class='tut_label' id='energize_target_self'>s1</span>)</code><span class='copy_code' code='s1.energize(s1);'>COPY</span> to your code. Hover over this snippet to learn more about what this does</p>",
	p2: "<p id='tut_helper' class='tutorial_text'>Nice, the spirit is now harvesting energy.</p><p id='tut_helper' class='tutorial_text'>Each spirit has a few properties that you can access and use to make decisions. Try it out—check whether spirit’s energy is equal to its energy_capacity and if yes, move it back to base.</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>if (s1.energy == s1.energy_capacity)</span> {<br>&nbsp;&nbsp;<span class='tut_label' id='spirit_reference'>s1</span><span class='tut_label' id='move_method'>.move</span>(<span class='tut_label' id='base_reference'>base</span><span class='tut_label' id='position_property'>.position</span>)<br>&nbsp;&nbsp;s1.energize(base);<br>}</code><br><span class='copy_code' code='if (s1.energy == s1.energy_capacity) {&#10;	s1.move(base.position)&#10;	s1.energize(base);&#10;}'>COPY</span></p>",
	p3: "<p id='tut_helper' class='tutorial_text'>Good, but you'll notice a problem. When the spirit transfers a little bit of energy to the star, the if statement returns false and the command to energize the base is ignored.</p><p id='tut_helper' class='tutorial_text'>Let’s fix this by using the <code><span class='tut_label' id='memory_intro0'>memory</span></code> object to store the spirit’s activity. <code><span class='tut_label' id='memory_intro1'>memory</span></code> is nothing more than an empty, pre-declared object. Add this to your code:</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>if (s1.energy == s1.energy_capacity){ <br>&nbsp;&nbsp; memory['s1'] = 'charging'; <br>} else if (s1.energy == 0){ <br>&nbsp;&nbsp; memory['s1'] = 'harvesting'; <br>}<br><br> if (memory['s1'] == 'charging'){ <br>&nbsp;&nbsp; s1.move(base.position); <br>&nbsp;&nbsp; s1.energize(base); <br>} else if (memory['s1'] == 'harvesting'){ <br>&nbsp;&nbsp; s1.move(star_zxq.position); <br>&nbsp;&nbsp; s1.energize(s1); <br>}</span></code><br><span class='copy_code' code='s1.energize(base);'>COPY</span></p>",
	//p4: "<p id='tut_helper' class='tutorial_text'>Hmm, that didn’t work. The code runs in a loop every tick where 1 tick = 1 second. So your variable is being re-declared over and over again. Luckily, you can use a <code><span class='tut_label' id='memory_intro'>memory</span></code> object to store values across ticks.</p><p id='tut_helper' class='tutorial_text'>Remove the var declaration and replace all other instances with a memory object instead, like this:</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>if (s1.energy == s1.energy_capacity){ <br>&nbsp;&nbsp; memory['s1'] = 'charging'; <br>} else if (s1.energy == 0){ <br>&nbsp;&nbsp; memory['s1'] = 'harvesting'; <br>}<br><br> if (memory['s1'] == 'charging'){ <br>&nbsp;&nbsp; s1.move(base.position); <br>&nbsp;&nbsp; s1.energize(base); <br>} else if (memory['s1'] == 'harvesting'){ <br>&nbsp;&nbsp; s1.move(star_zxq.position); <br>&nbsp;&nbsp; s1.energize(s1); <br>}</span></code><br><span class='copy_code' code='s1.energize(base);'>COPY</span></p>"
	p4: "<p id='tut_helper' class='tutorial_text'>Perfect, now the spirit is properly harvesting energy from the star and giving it to the base.</p><p id='tut_helper' class='tutorial_text'>Once your base’s energy reaches 100, it will be used to automatically create a new spirit.</p><p id='tut_helper' class='tutorial_text'>While you wait for that to happen, feel free to zoom in and out and pan around with your mouse. You are not alone, there is an enemy in the bottom right corner of the map.</p>",
	p5: "<p id='tut_helper' class='tutorial_text'>A new spirit s2 was born! Now you have two spirits to harvest the energy with.</p><p id='tut_helper' class='tutorial_text'>Instead of copying the entire code for the other spirit, you might want to create a loop. And instead of referring to your spirits as s1, s2, s3, ... let's use <code><span class='tut_label' id='my_spirits0'>my_spirits</span></code> array that contains all of your living spirits.</p><p id='tut_helper' class='tutorial_text'>Try writing this code on your own or <span class='copy_code' code='s1.energize(base);'>COPY</span> a possible solution.</p>",
	p6: "<p id='tut_helper' class='tutorial_text'>Well done, all your spirits should now autonomously harvest energy. <span class='tutorial_attack'>But wait! You are under attack!</span></p><p id='tut_helper' class='tutorial_text'>The spirits and the base have a .sight property. Spirits see units and structures within 400 radius, the base within 600 radius. What’s stored in sight are the ids, not the objects themselves. You can access the actual object with spirits(id).</p><p id='tut_helper' class='tutorial_text'>One spirit should be enough to deal with the invader. Add this to the end of your code:</p><p id='tut_helper' class='tutorial_text'><code><span class='tut_label' id='if_energy_capacity'>if (base.sight.enemies.length > 0){</span><br><span class='tut_label' id='if_energy_capacity'>&nbsp;&nbsp;var invader = spirits[base.sight.enemies[0]];</span><br><span class='tut_label' id='if_energy_capacity'>&nbsp;&nbsp;s1.move(invader.position);</span><br><span class='tut_label' id='if_energy_capacity'>&nbsp;&nbsp;s1.energize(invader);</span><br>}</code><br><span class='copy_code' code='s1.energize(base);'>COPY</span></p>",
	p7: "<p id='tut_helper' class='tutorial_text'>Excellent, your spirit will deal with the invader.</p><p id='tut_helper' class='tutorial_text'>Energy is used for both attacking and defending. When you attack an enemy unit, its energy will act as a shield. For every energy unit you attack with, 2 energy units are removed from the enemy.</p><p id='tut_helper' class='tutorial_text'>Also, whenever your base spots an enemy spirit, it stops creating new spirits, keeping all of its energy to defend itself.</p>",
}
